// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#pragma once

#include "cx_only_listener.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCxOnlyListener final : ::djinni::JniInterface<::testsuite::CxOnlyListener, NativeCxOnlyListener> {
public:
    using CppType = std::shared_ptr<::testsuite::CxOnlyListener>;
    using CppOptType = std::shared_ptr<::testsuite::CxOnlyListener>;
    using JniType = jobject;

    using Boxed = NativeCxOnlyListener;

    ~NativeCxOnlyListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeCxOnlyListener>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeCxOnlyListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeCxOnlyListener();
    friend ::djinni::JniClass<NativeCxOnlyListener>;
    friend ::djinni::JniInterface<::testsuite::CxOnlyListener, NativeCxOnlyListener>;

};

}  // namespace djinni_generated
