// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#include "NativeCxOnlyListener.hpp"  // my header

namespace djinni_generated {

NativeCxOnlyListener::NativeCxOnlyListener() : ::djinni::JniInterface<::testsuite::CxOnlyListener, NativeCxOnlyListener>() {}

NativeCxOnlyListener::~NativeCxOnlyListener() = default;


}  // namespace djinni_generated
