// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primtypes.djinni

#pragma once

#include "assorted_primitives.hpp"

namespace testsuite {

public ref class AssortedPrimitives sealed : public Platform::Object {
public:
    property bool B;
    property int8 Eight;
    property int16 Sixteen;
    property int32 Thirtytwo;
    property int64 Sixtyfour;
    property float32 Fthirtytwo;
    property float64 Fsixtyfour;
    property Platform::IBox<bool>^ OB;
    property Platform::IBox<int8>^ OEight;
    property Platform::IBox<int16>^ OSixteen;
    property Platform::IBox<int32>^ OThirtytwo;
    property Platform::IBox<int64>^ OSixtyfour;
    property Platform::IBox<float32>^ OFthirtytwo;
    property Platform::IBox<float64>^ OFsixtyfour;

    AssortedPrimitives(bool b,
                       int8 eight,
                       int16 sixteen,
                       int32 thirtytwo,
                       int64 sixtyfour,
                       float32 fthirtytwo,
                       float64 fsixtyfour,
                       Platform::IBox<bool>^ oB,
                       Platform::IBox<int8>^ oEight,
                       Platform::IBox<int16>^ oSixteen,
                       Platform::IBox<int32>^ oThirtytwo,
                       Platform::IBox<int64>^ oSixtyfour,
                       Platform::IBox<float32>^ oFthirtytwo,
                       Platform::IBox<float64>^ oFsixtyfour) {
        this->B = b;
        this->Eight = eight;
        this->Sixteen = sixteen;
        this->Thirtytwo = thirtytwo;
        this->Sixtyfour = sixtyfour;
        this->Fthirtytwo = fthirtytwo;
        this->Fsixtyfour = fsixtyfour;
        this->OB = oB;
        this->OEight = oEight;
        this->OSixteen = oSixteen;
        this->OThirtytwo = oThirtytwo;
        this->OSixtyfour = oSixtyfour;
        this->OFthirtytwo = oFthirtytwo;
        this->OFsixtyfour = oFsixtyfour;
    }
    AssortedPrimitives() {}
internal:
    ::testsuite::AssortedPrimitives toCpp();
    static AssortedPrimitives^ fromCpp(const ::testsuite::AssortedPrimitives& value);

    bool Equals(AssortedPrimitives^ rhs);
};

}  // namespace testsuite
