// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#include "ClientInterface.h"  // my header
#include "ClientReturnedRecord.h"
#include <stdint.h>

namespace testsuite {


}  // namespace testsuite
