// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#pragma once

#include "ClientReturnedRecord.h"
#include <stdint.h>

namespace testsuite {

public interface class IClientInterface
{
public:
    virtual ClientReturnedRecord^ GetRecord (int64 recordId, Platform::String^ utf8string, Platform::String^ misc);
    virtual float64 IdentifierCheck (const Platform::Array<uint8_t>^ data, int32 r, int64 jret);
    virtual Platform::String^ ReturnStr ();
    virtual Platform::String^ MethTakingInterface (IClientInterface^ i);
    virtual Platform::String^ MethTakingOptionalInterface (IClientInterface^ i);
};

}  // namespace testsuite
