// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#include "Conflict.h"  // my header
#include "translation.h"

namespace testsuite {


}  // namespace testsuite
