// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

#include "Conflict.hpp"
#include <memory>

namespace testsuite {

public ref class Conflict sealed : public Platform::Object
{
public:
internal:
    Conflict(std::shared_ptr<::testsuite::Conflict> cppRef) : _cppRef(cppRef) {}
    std::shared_ptr<::testsuite::Conflict> cppRef() {return _cppRef;}
private:
    std::shared_ptr<::testsuite::Conflict> _cppRef;
};

}  // namespace testsuite
