// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#pragma once

#include "ConstantRecord.h"
#include "constants.hpp"

namespace testsuite {

/** Record containing constants */
public ref class Constants sealed : public Platform::Object {
public:
    property static bool Constants::BoolConstant {bool get() {return true;} } 

    property static int8 Constants::I8Constant {int8 get() {return 1;} } 

    property static int16 Constants::I16Constant {int16 get() {return 2;} } 

    property static int32 Constants::I32Constant {int32 get() {return 3;} } 

    property static int64 Constants::I64Constant {int64 get() {return 4;} } 

    property static float32 Constants::F32Constant {float32 get() {return 5.0;} } 

    property static float64 Constants::F64Constant {float64 get() {return 5.0;} } 

    property static Platform::IBox<bool>^ Constants::OptBoolConstant {Platform::IBox<bool>^ get() {return true;} } 

    property static Platform::IBox<int8>^ Constants::OptI8Constant {Platform::IBox<int8>^ get() {return 1;} } 

    property static Platform::IBox<int16>^ Constants::OptI16Constant {Platform::IBox<int16>^ get() {return 2;} } 

    property static Platform::IBox<int32>^ Constants::OptI32Constant {Platform::IBox<int32>^ get() {return 3;} } 

    property static Platform::IBox<int64>^ Constants::OptI64Constant {Platform::IBox<int64>^ get() {return 4;} } 

    property static Platform::IBox<float32>^ Constants::OptF32Constant {Platform::IBox<float32>^ get() {return 5.0;} } 

    property static Platform::IBox<float64>^ Constants::OptF64Constant {Platform::IBox<float64>^ get() {return 5.0;} } 

    property static Platform::String^ Constants::StringConstant {Platform::String^ get() {return "string-constant";} } 

    property static Platform::String^ Constants::OptStringConstant {Platform::String^ get() {return "string-constant";} } 

    property static ConstantRecord^ Constants::ObjectConstant {ConstantRecord^ get() {return ref new ConstantRecord(
        Constants::I32Constant /* SomeInteger */ ,
        Constants::StringConstant /* SomeString */ );} } 

    property static bool Constants::Dummy {bool get() {return false;} } 
    Constants() {}
internal:
    ::testsuite::Constants toCpp();
    static Constants^ fromCpp(const ::testsuite::Constants& value);
};

}  // namespace testsuite
