// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#include "Constants.h"  // my header
#include "translation.h"

namespace testsuite {


::testsuite::Constants Constants::toCpp() {
    return ::testsuite::Constants(
    );
}

Constants^ Constants::fromCpp(const ::testsuite::Constants& value) {
    Constants^ ret = ref new Constants();
    return ret;
}

}  // namespace testsuite
