// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#include "ConstantsInterface.h"  // my header
#include "ConstantRecord.h"
#include "translation.h"

namespace testsuite {

void ConstantsInterface::Dummy ()
{
    try {
        _cppRef->dummy();
    }
    catch(const std::exception& e) {
        throw ref new Platform::Exception(-1, transform<std::string, Platform::String^>()((std::string)e.what()));
    }
}

}  // namespace testsuite
