// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#include "ConstantRecord.h"  // my header
#include "translation.h"

namespace testsuite {


::testsuite::ConstantRecord ConstantRecord::toCpp() {
    return ::testsuite::ConstantRecord(
        transform<int32_t, int32>()(SomeInteger),
        transform<std::string, Platform::String^>()(SomeString));
}

ConstantRecord^ ConstantRecord::fromCpp(const ::testsuite::ConstantRecord& value) {
    ConstantRecord^ ret = ref new ConstantRecord();
    ret->SomeInteger = transform<int32_t, int32>()(value.some_integer);
    ret->SomeString = transform<std::string, Platform::String^>()(value.some_string);
    return ret;
}

}  // namespace testsuite
