// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#pragma once

namespace testsuite {

public interface class ICxOnlyListener
{
public:
};

}  // namespace testsuite
