// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#include "CxOnlyListener.h"  // my header

namespace testsuite {


}  // namespace testsuite
