// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#pragma once

#include "CxOnlyListener.h"
#include "cx_only_listener.hpp"
#include "translation.h"
#include <functional>

namespace System {

template<> class CxInterfaceProxy<::testsuite::CxOnlyListener> : public ::testsuite::CxOnlyListener
{
public:
    CxInterfaceProxy(::testsuite::ICxOnlyListener^ nativeRef)
    {
        native_call_nativeRef = [nativeRef]{ return nativeRef; };
    }
    ::testsuite::ICxOnlyListener^ nativeRef() { return native_call_nativeRef(); }
private:
    std::function<::testsuite::ICxOnlyListener^()> native_call_nativeRef;
};

}  // namespace System
