// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

#pragma once

#include "date_record.hpp"
#include Windows.Foundation.FoundationContract.winmd

namespace testsuite {

public ref class DateRecord sealed : public Platform::Object {
public:
    property Windows::Foundation::DateTime CreatedAt;

    DateRecord(Windows::Foundation::DateTime createdAt) {
        this->CreatedAt = createdAt;
    }
    DateRecord() {}
internal:
    ::testsuite::DateRecord toCpp();
    static DateRecord^ fromCpp(const ::testsuite::DateRecord& value);

    bool Equals(DateRecord^ rhs);

    int32 CompareTo(DateRecord^ rhs);
};

}  // namespace testsuite
