// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#pragma once

#include "Color.h"
#include "enum_usage_record.hpp"

namespace testsuite {

public ref class EnumUsageRecord sealed : public Platform::Object {
public:
    property Color E;
    property Platform::IBox<Color>^ O;
    property Windows::Foundation::Collections::IVector<Color>^ L;
    property Windows::Foundation::Collections::IIterable<Color>^ S;
    property Windows::Foundation::Collections::IMap<Color, Color>^ M;

    EnumUsageRecord(Color e,
                    Platform::IBox<Color>^ o,
                    Windows::Foundation::Collections::IVector<Color>^ l,
                    Windows::Foundation::Collections::IIterable<Color>^ s,
                    Windows::Foundation::Collections::IMap<Color, Color>^ m) {
        this->E = e;
        this->O = o;
        this->L = l;
        this->S = s;
        this->M = m;
    }
    EnumUsageRecord() {}
internal:
    ::testsuite::EnumUsageRecord toCpp();
    static EnumUsageRecord^ fromCpp(const ::testsuite::EnumUsageRecord& value);
};

}  // namespace testsuite
