// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#include "ExternInterface1.h"  // my header
#include "ClientInterface.h"
#include "ClientInterfaceProxy.h"
#include "ClientReturnedRecord.h"
#include "translation.h"

namespace testsuite {

::testsuite::ClientReturnedRecord^ ExternInterface1::Foo (::testsuite::IClientInterface^ i)
{
    try {
        auto cppRet = _cppRef->foo(transform<std::shared_ptr<::testsuite::ClientInterface>, ::testsuite::IClientInterface^>()(i));
        return transform<::testsuite::ClientReturnedRecord, ::testsuite::ClientReturnedRecord^>()(cppRet);
    }
    catch(const std::exception& e) {
        throw ref new Platform::Exception(-1, transform<std::string, Platform::String^>()((std::string)e.what()));
    }
}

}  // namespace testsuite
