// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#pragma once

#include "ClientInterface.h"
#include "ClientReturnedRecord.h"
#include "extern_interface_1.hpp"
#include <memory>

namespace testsuite {

public ref class ExternInterface1 sealed : public Platform::Object
{
public:
    ::testsuite::ClientReturnedRecord^ Foo (::testsuite::IClientInterface^ i);
internal:
    ExternInterface1(std::shared_ptr<::ExternInterface1> cppRef) : _cppRef(cppRef) {}
    std::shared_ptr<::ExternInterface1> cppRef() {return _cppRef;}
private:
    std::shared_ptr<::ExternInterface1> _cppRef;
};

}  // namespace testsuite
