// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#include "ExternInterface2.h"  // my header
#include "ExternRecordWithDerivings.h"
#include "TestHelpers.h"
#include "TestHelpersProxy.h"

namespace testsuite {


}  // namespace testsuite
