// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#include "ExtendedRecord.h"  // my header
#include "translation.h"

namespace testsuite {


::testsuite::ExtendedRecord ExtendedRecord::toCpp() {
    return ::testsuite::ExtendedRecord(
        transform<bool, bool>()(Foo));
}

ExtendedRecord^ ExtendedRecord::fromCpp(const ::testsuite::ExtendedRecord& value) {
    ExtendedRecord^ ret = ref new ExtendedRecord();
    ret->Foo = transform<bool, bool>()(value.foo);
    return ret;
}

}  // namespace testsuite
