// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#pragma once

#include "ExternInterface2.h"
#include "ExternRecordWithDerivings.h"
#include "TestHelpers.h"
#include "extern_interface_2.hpp"
#include "translation.h"
#include <functional>

namespace System {

template<> class CxInterfaceProxy<::ExternInterface2> : public ::ExternInterface2
{
public:
    CxInterfaceProxy(::testsuite::IExternInterface2^ nativeRef)
    {
        native_call_nativeRef = [nativeRef]{ return nativeRef; };
    }
    ::ExternRecordWithDerivings foo(const std::shared_ptr<::testsuite::TestHelpers> & i) override
    {
        auto nativeRet = nativeRef()->Foo(transform<std::shared_ptr<::testsuite::TestHelpers>, ::testsuite::TestHelpers^>()(i));
        return transform<::ExternRecordWithDerivings, ::testsuite::ExternRecordWithDerivings^>()(nativeRet);
    }
    ::testsuite::IExternInterface2^ nativeRef() { return native_call_nativeRef(); }
private:
    std::function<::testsuite::IExternInterface2^()> native_call_nativeRef;
};

}  // namespace System
