// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#include "InterfaceUsingExtendedRecord.h"  // my header
#include "ExtendedRecord.h"
#include "RecordUsingExtendedRecord.h"
#include "translation.h"

namespace testsuite {

ExtendedRecord^ InterfaceUsingExtendedRecord::Meth (ExtendedRecord^ er)
{
    try {
        auto cppRet = _cppRef->meth(transform<::testsuite::ExtendedRecord, ::testsuite::ExtendedRecord^>()(er));
        return transform<::testsuite::ExtendedRecord, ::testsuite::ExtendedRecord^>()(cppRet);
    }
    catch(const std::exception& e) {
        throw ref new Platform::Exception(-1, transform<std::string, Platform::String^>()((std::string)e.what()));
    }
}

}  // namespace testsuite
