// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

#pragma once

#include "map_date_record.hpp"
#include Windows.Foundation.FoundationContract.winmd

namespace testsuite {

public ref class MapDateRecord sealed : public Platform::Object {
public:
    property Windows::Foundation::Collections::IMap<Platform::String^, Windows::Foundation::DateTime>^ DatesById;

    MapDateRecord(Windows::Foundation::Collections::IMap<Platform::String^, Windows::Foundation::DateTime>^ datesById) {
        this->DatesById = datesById;
    }
    MapDateRecord() {}
internal:
    ::testsuite::MapDateRecord toCpp();
    static MapDateRecord^ fromCpp(const ::testsuite::MapDateRecord& value);
};

}  // namespace testsuite
