// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#pragma once

#include "map_list_record.hpp"

namespace testsuite {

public ref class MapListRecord sealed : public Platform::Object {
public:
    property Windows::Foundation::Collections::IVector<Windows::Foundation::Collections::IMap<Platform::String^, int64>^>^ MapList;

    MapListRecord(Windows::Foundation::Collections::IVector<Windows::Foundation::Collections::IMap<Platform::String^, int64>^>^ mapList) {
        this->MapList = mapList;
    }
    MapListRecord() {}
internal:
    ::testsuite::MapListRecord toCpp();
    static MapListRecord^ fromCpp(const ::testsuite::MapListRecord& value);
};

}  // namespace testsuite
