// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nested_collection.djinni

#include "NestedCollection.h"  // my header
#include "translation.h"

namespace testsuite {


::testsuite::NestedCollection NestedCollection::toCpp() {
    return ::testsuite::NestedCollection(
        transform<std::vector<std::unordered_set<std::string>>, Windows::Foundation::Collections::IVector<Windows::Foundation::Collections::IIterable<Platform::String^>^>^>()(SetList));
}

NestedCollection^ NestedCollection::fromCpp(const ::testsuite::NestedCollection& value) {
    NestedCollection^ ret = ref new NestedCollection();
    ret->SetList = transform<std::vector<std::unordered_set<std::string>>, Windows::Foundation::Collections::IVector<Windows::Foundation::Collections::IIterable<Platform::String^>^>^>()(value.set_list);
    return ret;
}

}  // namespace testsuite
