// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primitive_list.djinni

#pragma once

#include "primitive_list.hpp"

namespace testsuite {

public ref class PrimitiveList sealed : public Platform::Object {
public:
    property Windows::Foundation::Collections::IVector<int64>^ List;

    PrimitiveList(Windows::Foundation::Collections::IVector<int64>^ list) {
        this->List = list;
    }
    PrimitiveList() {}
internal:
    ::testsuite::PrimitiveList toCpp();
    static PrimitiveList^ fromCpp(const ::testsuite::PrimitiveList& value);
};

}  // namespace testsuite
