// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

#pragma once

#include "record_with_derivings.hpp"

namespace testsuite {

public ref class RecordWithDerivings sealed : public Platform::Object {
public:
    property int8 Eight;
    property int16 Sixteen;
    property int32 Thirtytwo;
    property int64 Sixtyfour;
    property float32 Fthirtytwo;
    property float64 Fsixtyfour;
    property Windows::Foundation::DateTime^ D;
    property Platform::String^ S;

    RecordWithDerivings(int8 eight,
                        int16 sixteen,
                        int32 thirtytwo,
                        int64 sixtyfour,
                        float32 fthirtytwo,
                        float64 fsixtyfour,
                        Windows::Foundation::DateTime^ d,
                        Platform::String^ s) {
        this->Eight = eight;
        this->Sixteen = sixteen;
        this->Thirtytwo = thirtytwo;
        this->Sixtyfour = sixtyfour;
        this->Fthirtytwo = fthirtytwo;
        this->Fsixtyfour = fsixtyfour;
        this->D = d;
        this->S = s;
    }
    RecordWithDerivings() {}
internal:
    ::testsuite::RecordWithDerivings toCpp();
    static RecordWithDerivings^ fromCpp(const ::testsuite::RecordWithDerivings& value);

    bool Equals(RecordWithDerivings^ rhs);

    int32 CompareTo(RecordWithDerivings^ rhs);
};

}  // namespace testsuite
