// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#pragma once

#include "ExtendedRecord.h"
#include "record_using_extended_record.hpp"

namespace testsuite {

public ref class RecordUsingExtendedRecord sealed : public Platform::Object {
public:
    property static RecordUsingExtendedRecord^ RecordUsingExtendedRecord::Cr {RecordUsingExtendedRecord^ get() {return ref new RecordUsingExtendedRecord(
        ref new ExtendedRecord(
            false /* Foo */ ) /* Er */ );} } 
    property ExtendedRecord^ Er;

    RecordUsingExtendedRecord(ExtendedRecord^ er) {
        this->Er = er;
    }
    RecordUsingExtendedRecord() {}
internal:
    ::testsuite::RecordUsingExtendedRecord toCpp();
    static RecordUsingExtendedRecord^ fromCpp(const ::testsuite::RecordUsingExtendedRecord& value);
};

}  // namespace testsuite
