// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#include "RecordUsingExtendedRecord.h"  // my header
#include "translation.h"

namespace testsuite {


::testsuite::RecordUsingExtendedRecord RecordUsingExtendedRecord::toCpp() {
    return ::testsuite::RecordUsingExtendedRecord(
        transform<::testsuite::ExtendedRecord, ::testsuite::ExtendedRecord^>()(Er));
}

RecordUsingExtendedRecord^ RecordUsingExtendedRecord::fromCpp(const ::testsuite::RecordUsingExtendedRecord& value) {
    RecordUsingExtendedRecord^ ret = ref new RecordUsingExtendedRecord();
    ret->Er = transform<::testsuite::ExtendedRecord, ::testsuite::ExtendedRecord^>()(value.er);
    return ret;
}

}  // namespace testsuite
