// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#pragma once

#include "return_one.hpp"
#include <memory>

namespace testsuite {

public ref class ReturnOne sealed : public Platform::Object
{
public:
    static ReturnOne^ GetInstance ();
    int8 ReturnOne ();
internal:
    ReturnOne(std::shared_ptr<::testsuite::ReturnOne> cppRef) : _cppRef(cppRef) {}
    std::shared_ptr<::testsuite::ReturnOne> cppRef() {return _cppRef;}
private:
    std::shared_ptr<::testsuite::ReturnOne> _cppRef;
};

}  // namespace testsuite
