// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

#include "AssortedPrimitives.h"
#include "ClientInterfaceProxy.h"
#include "Color.h"
#include "MapListRecord.h"
#include "NestedCollection.h"
#include "PrimitiveList.h"
#include "SetRecord.h"
#include "UserTokenProxy.h"
#include "test_helpers.hpp"
#include <memory>
#include <stdint.h>

namespace testsuite {

public ref class TestHelpers sealed : public Platform::Object
{
public:
    static SetRecord^ GetSetRecord ();
    static bool CheckSetRecord (SetRecord^ rec);
    static PrimitiveList^ GetPrimitiveList ();
    static bool CheckPrimitiveList (PrimitiveList^ pl);
    static NestedCollection^ GetNestedCollection ();
    static bool CheckNestedCollection (NestedCollection^ nc);
    static Windows::Foundation::Collections::IMap<Platform::String^, int64>^ GetMap ();
    static bool CheckMap (Windows::Foundation::Collections::IMap<Platform::String^, int64>^ m);
    static Windows::Foundation::Collections::IMap<Platform::String^, int64>^ GetEmptyMap ();
    static bool CheckEmptyMap (Windows::Foundation::Collections::IMap<Platform::String^, int64>^ m);
    static MapListRecord^ GetMapListRecord ();
    static bool CheckMapListRecord (MapListRecord^ m);
    static void CheckClientInterfaceAscii (IClientInterface^ i);
    static void CheckClientInterfaceNonascii (IClientInterface^ i);
    static void CheckClientInterfaceArgs (IClientInterface^ i);
    static void CheckEnumMap (Windows::Foundation::Collections::IMap<Color, Platform::String^>^ m);
    static void CheckEnum (Color c);
    static IUserToken^ TokenId (IUserToken^ t);
    static IUserToken^ CreateCppToken ();
    static void CheckCppToken (IUserToken^ t);
    static int64 CppTokenId (IUserToken^ t);
    static void CheckTokenType (IUserToken^ t, Platform::String^ type);
    static Platform::IBox<int32>^ ReturnNone ();
    static AssortedPrimitives^ AssortedPrimitivesId (AssortedPrimitives^ i);
    static Platform::Array<uint8_t>^ IdBinary (const Platform::Array<uint8_t>^ b);
internal:
    TestHelpers(std::shared_ptr<::testsuite::TestHelpers> cppRef) : _cppRef(cppRef) {}
    std::shared_ptr<::testsuite::TestHelpers> cppRef() {return _cppRef;}
private:
    std::shared_ptr<::testsuite::TestHelpers> _cppRef;
};

}  // namespace testsuite
