// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#pragma once

#include "../../handwritten-src/cpp/optional.hpp"
template<typename T> using djinni_optional = std::experimental::optional<T>;
#include "translate.h"
using namespace System;

namespace testsuite {


}  // namespace testsuite
