// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user_token.djinni

#pragma once

#include "user_token.hpp"
#include <memory>

namespace testsuite {

public ref class UserToken sealed : public Platform::Object
{
public:
    Platform::String^ Whoami ();
internal:
    UserToken(std::shared_ptr<::testsuite::UserToken> cppRef) : _cppRef(cppRef) {}
    std::shared_ptr<::testsuite::UserToken> cppRef() {return _cppRef;}
private:
    std::shared_ptr<::testsuite::UserToken> _cppRef;
};

}  // namespace testsuite
