// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from varnames.djinni

#pragma once

#include "VarnameRecord.h"
#include "_varname_interface_.hpp"
#include <memory>

namespace testsuite {

public ref class VarnameInterface sealed : public Platform::Object
{
public:
    VarnameRecord^ Rmethod (VarnameRecord^ RArg);
    VarnameInterface^ Imethod (VarnameInterface^ IArg);
internal:
    VarnameInterface(std::shared_ptr<::testsuite::VarnameInterface> cppRef) : _cppRef(cppRef) {}
    std::shared_ptr<::testsuite::VarnameInterface> cppRef() {return _cppRef;}
private:
    std::shared_ptr<::testsuite::VarnameInterface> _cppRef;
};

}  // namespace testsuite
