// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from varnames.djinni

#include "VarnameInterface.h"  // my header
#include "VarnameRecord.h"
#include "translation.h"

namespace testsuite {

VarnameRecord^ VarnameInterface::Rmethod (VarnameRecord^ RArg)
{
    try {
        auto cppRet = _cppRef->_rmethod_(transform<::testsuite::VarnameRecord, ::testsuite::VarnameRecord^>()(RArg));
        return transform<::testsuite::VarnameRecord, ::testsuite::VarnameRecord^>()(cppRet);
    }
    catch(const std::exception& e) {
        throw ref new Platform::Exception(-1, transform<std::string, Platform::String^>()((std::string)e.what()));
    }
}
VarnameInterface^ VarnameInterface::Imethod (VarnameInterface^ IArg)
{
    try {
        auto cppRet = _cppRef->_imethod_(transform<std::shared_ptr<::testsuite::VarnameInterface>, ::testsuite::VarnameInterface^>()(IArg));
        return transform<std::shared_ptr<::testsuite::VarnameInterface>, ::testsuite::VarnameInterface^>()(cppRet);
    }
    catch(const std::exception& e) {
        throw ref new Platform::Exception(-1, transform<std::string, Platform::String^>()((std::string)e.what()));
    }
}

}  // namespace testsuite
