// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from varnames.djinni

#include "VarnameRecord.h"  // my header
#include "translation.h"

namespace testsuite {


::testsuite::VarnameRecord VarnameRecord::toCpp() {
    return ::testsuite::VarnameRecord(
        transform<int8_t, int8>()(Field));
}

VarnameRecord^ VarnameRecord::fromCpp(const ::testsuite::VarnameRecord& value) {
    VarnameRecord^ ret = ref new VarnameRecord();
    ret->Field = transform<int8_t, int8>()(value._field_);
    return ret;
}

}  // namespace testsuite
