// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni

#pragma once

#include "wchar_test_rec.hpp"

namespace testsuite {

public ref class WcharTestRec sealed : public Platform::Object {
public:
    property Platform::String^ S;

    WcharTestRec(Platform::String^ s) {
        this->S = s;
    }
    WcharTestRec() {}
internal:
    ::testsuite::WcharTestRec toCpp();
    static WcharTestRec^ fromCpp(const ::testsuite::WcharTestRec& value);
};

}  // namespace testsuite
