// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni

#pragma once

#include "WcharTestRec.h"
#include "wchar_test_helpers.hpp"
#include <memory>

namespace testsuite {

public ref class WcharTestHelpers sealed : public Platform::Object
{
public:
    static WcharTestRec^ GetRecord ();
    static Platform::String^ GetString ();
    static bool CheckString (Platform::String^ str);
    static bool CheckRecord (WcharTestRec^ rec);
internal:
    WcharTestHelpers(std::shared_ptr<::testsuite::WcharTestHelpers> cppRef) : _cppRef(cppRef) {}
    std::shared_ptr<::testsuite::WcharTestHelpers> cppRef() {return _cppRef;}
private:
    std::shared_ptr<::testsuite::WcharTestHelpers> _cppRef;
};

}  // namespace testsuite
