// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni

#include "WcharTestRec.h"  // my header
#include "translation.h"

namespace testsuite {


::testsuite::WcharTestRec WcharTestRec::toCpp() {
    return ::testsuite::WcharTestRec(
        transform<std::wstring, Platform::String^>()(S));
}

WcharTestRec^ WcharTestRec::fromCpp(const ::testsuite::WcharTestRec& value) {
    WcharTestRec^ ret = ref new WcharTestRec();
    ret->S = transform<std::wstring, Platform::String^>()(value.s);
    return ret;
}

}  // namespace testsuite
