// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#import "DBConstants.h"


BOOL const DBConstantsBoolConstant = YES;

int8_t const DBConstantsI8Constant = 1;

int16_t const DBConstantsI16Constant = 2;

int32_t const DBConstantsI32Constant = 3;

int64_t const DBConstantsI64Constant = 4;

float const DBConstantsF32Constant = 5.0f;

double const DBConstantsF64Constant = 5.0;

NSString * __nonnull const DBConstantsStringConstant = @"string-constant";

@implementation DBConstants

- (nonnull instancetype)initWithSomeInteger:(int32_t)someInteger
                                 someString:(nonnull NSString *)someString
{
    if (self = [super init]) {
        _someInteger = someInteger;
        _someString = [someString copy];
    }
    return self;
}

+ (nonnull instancetype)constantsWithSomeInteger:(int32_t)someInteger
                                      someString:(nonnull NSString *)someString
{
    return [[self alloc] initWithSomeInteger:someInteger
                                  someString:someString];
}

+ (NSNumber * __nullable)optionalIntegerConstant
{
    static NSNumber * const s_optionalIntegerConstant = @1;
    return s_optionalIntegerConstant;
}

+ (DBConstants * __nonnull)objectConstant
{
    static DBConstants * const s_objectConstant = [[DBConstants alloc] initWithSomeInteger:DBConstantsI32Constant
            someString:DBConstantsStringConstant];
    return s_objectConstant;
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p someInteger:%@ someString:%@>", self.class, (void *)self, @(self.someInteger), self.someString];
}

@end
