// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#import <Foundation/Foundation.h>
@class DBCxOnlyListener;
@class DBJavaOnlyListener;
@protocol DBObjcOnlyListener;


/**
 * Generating and compiling this makes sure other languages don't break
 * on references to interfaces they don't need.
 */
@protocol DBUsesSingleLanguageListeners

- (void)callForObjC:(nullable id<DBObjcOnlyListener>)l;

- (nullable id<DBObjcOnlyListener>)returnForObjC;

- (void)callForJava:(nullable DBJavaOnlyListener *)l;

- (nullable DBJavaOnlyListener *)returnForJava;

- (void)callForCx:(nullable DBCxOnlyListener *)l;

- (nullable DBCxOnlyListener *)returnForCx;

@end
